import { el, replaceChildren } from "./ui.js";
import { ASSURANCE_LABEL } from "./resultCard.js";
import type { Headline, Summary } from "./summary.js";

export type SheetContext = {
  transactionHash: string;
  checkedAt: Date;
  blockNumber?: bigint | undefined;
};

export type Sheet = {
  element: HTMLElement;
  update(summary: Summary, context: SheetContext): void;
};

const STAMP: Record<Headline, string> = {
  VERIFIED: "Verified",
  NOT_VERIFIED: "Not verified",
  INSUFFICIENT_EVIDENCE: "Insufficient evidence",
  CONFLICT: "Evidence conflict",
  NO_RESULT: "No result",
  PENDING: "Checking",
};

const GLYPH: Record<string, string> = { PASS: "✓", FAIL: "✕", ABSTAIN: "–" };
const NAME: Record<string, string> = {
  transactionHash: "Transaction",
  chainId: "Chain",
  execution: "Execution",
  sender: "Sender",
  recipient: "Recipient",
  asset: "Asset",
  amount: "Amount",
};

const utc = (date: Date): string => `${date.toISOString().slice(0, 19).replace("T", " ")} UTC`;

/**
 * The case file: one stamp, one sentence, and the seven checks at a glance. It only restates what the
 * tiers below established; the per-tier detail stays below it, and this view never outranks it.
 */
export function createSheet(actions: { copyLink: () => Promise<boolean>; print: () => void }): Sheet {
  const body = el("div", { class: "sheet-body" });
  const element = el("section", { class: "sheet paper", "aria-labelledby": "case-heading" }, el("h2", { id: "case-heading", class: "eyebrow" }, "Case file"), body);

  // The stamp lands once per verdict change; re-renders with the same verdict stay still.
  let lastHeadline: Headline | null = null;
  const copied = el("span", { class: "hint", role: "status" });
  const copy = el("button", { type: "button", class: "secondary" }, "Copy link to this check");
  copy.addEventListener("click", async () => {
    copied.textContent = (await actions.copyLink()) ? "Link copied." : "Couldn't copy. The address bar has the link.";
  });
  const print = el("button", { type: "button", class: "secondary" }, "Print or save as PDF");
  print.addEventListener("click", () => actions.print());

  return {
    element,
    update(summary, context) {
      copied.textContent = "";
      const meta = el(
        "dl",
        { class: "case-meta" },
        el("div", {}, el("dt", {}, "Transaction"), el("dd", { class: "mono" }, context.transactionHash)),
        el("div", {}, el("dt", {}, "Network"), el("dd", {}, "Monad testnet (chain 10143)")),
        ...(context.blockNumber !== undefined
          ? [el("div", {}, el("dt", {}, "Block"), el("dd", { class: "mono" }, context.blockNumber.toLocaleString("en-US")))]
          : []),
        el("div", {}, el("dt", {}, "Checked"), el("dd", {}, utc(context.checkedAt))),
      );

      const changed = summary.headline !== lastHeadline;
      lastHeadline = summary.headline;
      const stamp = el(
        "p",
        { class: changed && summary.headline !== "PENDING" ? "stamp stamp-in" : "stamp", "data-verdict": summary.headline },
        el("span", { class: "sr-only" }, "Result: "),
        STAMP[summary.headline],
      );
      const scope =
        summary.assurance !== undefined
          ? el("p", { class: "scope" }, "Evidence level: ", el("strong", { class: "mono" }, summary.assurance), ` (${ASSURANCE_LABEL[summary.assurance]})`)
          : el("p", { class: "scope" }, "No evidence level reached.");

      const checks =
        summary.checks === undefined
          ? []
          : [
              el(
                "ul",
                { class: "check-grid", "aria-label": "Checks at a glance" },
                ...summary.checks.map((check) =>
                  el(
                    "li",
                    { "data-status": check.status },
                    el("span", { class: "glyph", "aria-hidden": "true" }, GLYPH[check.status] ?? "?"),
                    el("span", { class: "check-name" }, NAME[check.name] ?? check.name),
                    el("span", { class: "check-status" }, check.status),
                  ),
                ),
              ),
            ];

      replaceChildren(
        body,
        meta,
        el("div", { class: "verdict-block" }, stamp, el("div", { class: "verdict-text" }, el("p", { class: "sentence" }, summary.sentence), scope)),
        ...(summary.stillChecking ? [el("p", { class: "hint" }, "Stronger evidence is still being checked; this may change.")] : []),
        ...checks,
        el(
          "div",
          { class: "sheet-actions" },
          copy,
          print,
          copied,
        ),
        el(
          "p",
          { class: "print-only scope-note" },
          "Generated by Veridra from evidence read via testnet-rpc.monad.xyz. A ledger fact is not proof of wallet ownership, legal settlement or delivery.",
        ),
      );
    },
  };
}
